In [1]:
#modules necessaires
import numpy as np 
import pandas as pd
import os
for dirname, _, filenames in os.walk('Position_Salaries.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
#dataset
dataset = pd.read_csv('Position_Salaries.csv')
dataset.head()

Position  Level  Salary
0   Project Analyste      1   45000
1          Ingenieur      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [3]:
#s'il y a des valeures nules
dataset.isnull()

Position  Level  Salary
0     False  False   False
1     False  False   False
2     False  False   False
3     False  False   False
4     False  False   False
5     False  False   False
6     False  False   False
7     False  False   False
8     False  False   False
9     False  False   False

In [4]:
#eneleve les colonnes inutiles
dataset.drop(['Position'], axis=1, inplace=True)

In [5]:
dataset.head()

Level  Salary
0      1   45000
1      2   50000
2      3   60000
3      4   80000
4      5  110000

In [6]:
# transformation en 0 ou 1
dataset_ = pd.get_dummies(dataset['Salary'], drop_first=True)
dataset = pd.concat([dataset_, dataset], axis = 1)
dataset.drop(['Salary'], axis=1, inplace=True)
dataset

50000  60000  80000  110000  150000  200000  300000  500000  1000000  Level
0      0      0      0       0       0       0       0       0        0      1
1      1      0      0       0       0       0       0       0        0      2
2      0      1      0       0       0       0       0       0        0      3
3      0      0      1       0       0       0       0       0        0      4
4      0      0      0       1       0       0       0       0        0      5
5      0      0      0       0       1       0       0       0        0      6
6      0      0      0       0       0       1       0       0        0      7
7      0      0      0       0       0       0       1       0        0      8
8      0      0      0       0       0       0       0       1        0      9
9      0      0      0       0       0       0       0       0        1     10

In [7]:
#assignation de X et y
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values

In [8]:
#séparation en deux parties entrainement / test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [9]:
#entrainement
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
# Polynomial 
PolyReg = PolynomialFeatures(degree = 4)
X_poly = PolyReg.fit_transform(X_train)
# Linear
LinearReg = LinearRegression()
LinearReg.fit(X_poly, y_train)

LinearRegression()

In [10]:
#prédiction du résultat
LinearReg.predict(PolyReg.fit_transform(X_test))

array([[1.],
       [1.]])

In [11]:
# Coefficients et intercepteurs
coefficient = LinearReg.coef_
interceptors = LinearReg.intercept_
print(coefficient)

[[-3.33066907e-16  2.50000000e-01 -8.88178420e-16  7.50000000e-01
   1.00000000e+00  1.25000000e+00  1.50000000e+00  1.75000000e+00
   2.00000000e+00  0.00000000e+00  2.50000000e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  7.50000000e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.25000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.50000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.75000000e+00  0.00000000e+00  0.00000000e+00
   2.00000000e+00  0.00000000e+00  0.00000000e+00  2.50000000e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000

In [12]:
print(interceptors)

[1.]


# vin rouge

In [13]:
#dataset
dataset = pd.read_csv('qualite-vin-rouge.csv')
dataset.head()

acidité fixe  acidité volatile  acide citrique  sucre résiduel  chlorures  \
0           7.4              0.70            0.00             1.9      0.076   
1           7.8              0.88            0.00             2.6      0.098   
2           7.8              0.76            0.04             2.3      0.092   
3          11.2              0.28            0.56             1.9      0.075   
4           7.4              0.70            0.00             1.9      0.076   

   dioxyde de soufre libre  anhydride sulfureux total  densité    pH  \
0                     11.0                       34.0   0.9978  3.51   
1                     25.0                       67.0   0.9968  3.20   
2                     15.0                       54.0   0.9970  3.26   
3                     17.0                       60.0   0.9980  3.16   
4                     11.0                       34.0   0.9978  3.51   

   sulphates  alcool  qualité  
0       0.56     9.4        5  
1       0.68     9.8        5  
2       0.65     9.8        5  
3       0.58     9.8        6  
4       0.56     9.4        5

In [14]:
#s'il y a des valeures nules
dataset.isnull()

acidité fixe  acidité volatile  acide citrique  sucre résiduel  \
0            False             False           False           False   
1            False             False           False           False   
2            False             False           False           False   
3            False             False           False           False   
4            False             False           False           False   
...            ...               ...             ...             ...   
1594         False             False           False           False   
1595         False             False           False           False   
1596         False             False           False           False   
1597         False             False           False           False   
1598         False             False           False           False   

      chlorures  dioxyde de soufre libre  anhydride sulfureux total  densité  \
0         False                    False                      False    False   
1         False                    False                      False    False   
2         False                    False                      False    False   
3         False                    False                      False    False   
4         False                    False                      False    False   
...         ...                      ...                        ...      ...   
1594      False                    False                      False    False   
1595      False                    False                      False    False   
1596      False                    False                      False    False   
1597      False                    False                      False    False   
1598      False                    False                      False    False   

         pH  sulphates  alcool  qualité  
0     False      False   False    False  
1     False      False   False    False  
2     False      False   False    False  
3     False      False   False    False  
4     False      False   False    False  
...     ...        ...     ...      ...  
1594  False      False   False    False  
1595  False      False   False    False  
1596  False      False   False    False  
1597  False      False   False    False  
1598  False      False   False    False  

[1599 rows x 12 columns]

In [15]:
# transformation en 0 ou 1
dataset_ = pd.get_dummies(dataset['qualité'], drop_first=True)
dataset = pd.concat([dataset_, dataset], axis = 1)
dataset.drop(['qualité'], axis=1, inplace=True)
dataset

4  5  6  7  8  acidité fixe  acidité volatile  acide citrique  \
0     0  1  0  0  0           7.4             0.700            0.00   
1     0  1  0  0  0           7.8             0.880            0.00   
2     0  1  0  0  0           7.8             0.760            0.04   
3     0  0  1  0  0          11.2             0.280            0.56   
4     0  1  0  0  0           7.4             0.700            0.00   
...  .. .. .. .. ..           ...               ...             ...   
1594  0  1  0  0  0           6.2             0.600            0.08   
1595  0  0  1  0  0           5.9             0.550            0.10   
1596  0  0  1  0  0           6.3             0.510            0.13   
1597  0  1  0  0  0           5.9             0.645            0.12   
1598  0  0  1  0  0           6.0             0.310            0.47   

      sucre résiduel  chlorures  dioxyde de soufre libre  \
0                1.9      0.076                     11.0   
1                2.6      0.098                     25.0   
2                2.3      0.092                     15.0   
3                1.9      0.075                     17.0   
4                1.9      0.076                     11.0   
...              ...        ...                      ...   
1594             2.0      0.090                     32.0   
1595             2.2      0.062                     39.0   
1596             2.3      0.076                     29.0   
1597             2.0      0.075                     32.0   
1598             3.6      0.067                     18.0   

      anhydride sulfureux total  densité    pH  sulphates  alcool  
0                          34.0  0.99780  3.51       0.56     9.4  
1                          67.0  0.99680  3.20       0.68     9.8  
2                          54.0  0.99700  3.26       0.65     9.8  
3                          60.0  0.99800  3.16       0.58     9.8  
4                          34.0  0.99780  3.51       0.56     9.4  
...                         ...      ...   ...        ...     ...  
1594                       44.0  0.99490  3.45       0.58    10.5  
1595                       51.0  0.99512  3.52       0.76    11.2  
1596                       40.0  0.99574  3.42       0.75    11.0  
1597                       44.0  0.99547  3.57       0.71    10.2  
1598                       42.0  0.99549  3.39       0.66    11.0  

[1599 rows x 16 columns]

In [16]:
#assignation de X et y
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values

In [17]:
print(X)
print(y)

[[0.      1.      0.      ... 0.9978  3.51    0.56   ]
 [0.      1.      0.      ... 0.9968  3.2     0.68   ]
 [0.      1.      0.      ... 0.997   3.26    0.65   ]
 ...
 [0.      0.      1.      ... 0.99574 3.42    0.75   ]
 [0.      1.      0.      ... 0.99547 3.57    0.71   ]
 [0.      0.      1.      ... 0.99549 3.39    0.66   ]]
[[ 9.4]
 [ 9.8]
 [ 9.8]
 ...
 [11. ]
 [10.2]
 [11. ]]


In [18]:
#séparation en deux parties entrainement / test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [19]:
#entrainement
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
# Polynomial 
PolyReg = PolynomialFeatures(degree = 4)
X_poly = PolyReg.fit_transform(X_train)
# Linear
LinearReg = LinearRegression()
LinearReg.fit(X_poly, y_train)

LinearRegression()

In [20]:
#prédiction du résultat
LinearReg.predict(PolyReg.fit_transform(X_test))

array([[ 1.05002627e+01],
       [ 1.29668100e+01],
       [ 2.31994370e+01],
       [ 1.04030633e+01],
       [ 1.14009452e+01],
       [ 4.34542241e+00],
       [ 1.26276370e+01],
       [-2.96524004e+00],
       [-1.46815681e+02],
       [ 1.14803322e+01],
       [ 9.11584152e+00],
       [ 8.86367490e+00],
       [ 1.08606099e+01],
       [ 1.09004275e+01],
       [ 9.43366338e+00],
       [ 1.04842598e+01],
       [ 6.16391249e+00],
       [ 1.04803327e+01],
       [ 1.23106012e+01],
       [ 1.01987368e+01],
       [ 9.20155698e+00],
       [-9.48990360e-01],
       [ 9.70401087e+00],
       [ 1.89211816e+01],
       [ 5.16178425e+00],
       [ 9.89203777e+00],
       [ 3.99342447e+00],
       [ 1.77906967e+01],
       [ 1.07746064e+01],
       [-1.66507271e+02],
       [ 9.86079083e+00],
       [ 1.08988110e+01],
       [ 1.71768374e+01],
       [ 1.33673466e+01],
       [-3.81022220e+01],
       [ 1.55804040e+01],
       [ 9.39865206e+00],
       [ 1.02322412e+01],
       [ 1.5

In [21]:
# Coefficients et intercepteurs
coefficient = LinearReg.coef_
interceptors = LinearReg.intercept_
print(coefficient)

[[-1.18188215e-02 -2.03913355e-02  4.79431004e+00 ... -8.66707811e+01
   1.21752621e+02 -4.86550777e+01]]


In [22]:
print(interceptors)

[1359.24677578]
